### ISSUE TITLE
Feature req: Specify scrapes for only webtorrents

### ISSUE THREAD

**Issue by 34r7h** [JimmyLaurent/torrent-search-api#101]
Hi, thanks for this work. Well done. I'm using it on a cloud function that returns results and magnet links to a browser running webtorrents. Is there a way or recommended provider that gives only webtorrent format results?

**Comment by JimmyLaurent** [comment]
Hi,
This library scrape torrents from different providers (thepiratebay, etc...), if the provider doesn't give us this information, I'm affraid it's not possible to have it.

If your ultimate goal is to download torrents from your browser, maybe you can check out projects like [peerflix-server](https://github.com/asapach/peerflix-server).

**Comment by 34r7h** [comment]
thanks @JimmyLaurent i'll check
