### ISSUE TITLE
Rarbg not working anymore

### ISSUE THREAD

**Issue by florinutz** [JimmyLaurent/torrent-search-api#103]
The api is down, so the whole provider is broken. They have a protection against crawlers which, among other checks, checks for visibility of the current browser tab, so not even a headless browser will do.

**Comment by JimmyLaurent** [comment]
I just tested it and it works fine for me.

Can you reach this url with your browser ? => https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=NodeTorrentSearchApi
