### ISSUE TITLE
TypeError: TorrentSearchApi is not a function

### ISSUE THREAD

**Issue by ajanjairam** [JimmyLaurent/torrent-search-api#105]
const TorrentSearchApi = require('torrent-search-api');
TorrentSearchApi.enableProvider('Torrent9');
async function getTorrents() {
const torrents = await TorrentSearchApi('1080', 'Movies', 20);
const result = await TorrentSearchApi.getTorrentDetails(torrents);
console.log(result);
}
getTorrents()

**_The above code gives the below error_**

**(node:38300) UnhandledPromiseRejectionWarning: TypeError: TorrentSearchApi is not a function**

**Comment by JimmyLaurent** [comment]
You have an error in your code:
```js
const TorrentSearchApi = require('torrent-search-api');

TorrentSearchApi.enableProvider('Torrent9');
async function getTorrents() {
    const torrents = await TorrentSearchApi('1080', 'Movies', 20); // <= TorrentSearchApi.search('1080', 'Movies', 20)
    const result = await TorrentSearchApi.getTorrentDetails(torrents);
    console.log(result);
}
getTorrents()
```

**Comment by ajanjairam** [comment]
> You have an error in your code:
> 
> ```js
> const TorrentSearchApi = require('torrent-search-api');
> 
> TorrentSearchApi.enableProvider('Torrent9');
> async function getTorrents() {
>     const torrents = await TorrentSearchApi('1080', 'Movies', 20); // <= TorrentSearchApi.search('1080', 'Movies', 20)
>     const result = await TorrentSearchApi.getTorrentDetails(torrents);
>     console.log(result);
> }
> getTorrents()
> ```

Can you specify the error ?

**Comment by JimmyLaurent** [comment]
There's a comment on this line ;)

```js
 const torrents = await TorrentSearchApi('1080', 'Movies', 20); // <= TorrentSearchApi.search('1080', 'Movies', 20)
```

**Comment by ajanjairam** [comment]
> There's a comment on this line ;)
> 
> ```js
>  const torrents = await TorrentSearchApi('1080', 'Movies', 20); // <= TorrentSearchApi.search('1080', 'Movies', 20)
> ```

Thanks a lot.

**Comment by ajanjairam** [comment]
> 
> 
> There's a comment on this line ;)
> 
> ```js
>  const torrents = await TorrentSearchApi('1080', 'Movies', 20); // <= TorrentSearchApi.search('1080', 'Movies', 20)
> ```

const TorrentSearchApi = require('torrent-search-api');
TorrentSearchApi.enableProvider('Torrent9');
async function getTorrents() {
    const torrents = await TorrentSearchApi.search('1080', 'Movies', 20);
    const result = await TorrentSearchApi.getTorrentDetails(torrents);
    console.log(result);
}
getTorrents()

i corrected the error code to the above code, and this gives an new error !
(node:11940) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at exports.uniqueName (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\utils\helpers.js:1:35)
    at C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:147:35
    at baseFindIndex (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\lodash\lodash.js:802:11)
    at findIndex (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\lodash\lodash.js:7258:14)
    at ProviderManager.getProvider (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:145:24)       
    at ProviderManager.getTorrentDetails (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:126:17) 
    at getTorrents (C:\Users\Ajan JaiRam\Desktop\TelegramBot\eg1.js:5:43)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\Ajan JaiRam\Desktop\TelegramBot> node eg1.js
(node:9304) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at exports.uniqueName (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\utils\helpers.js:1:35)
    at C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:147:35
    at baseFindIndex (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\lodash\lodash.js:802:11)
    at findIndex (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\lodash\lodash.js:7258:14)
    at Function.find (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\lodash\lodash.js:5059:21)
    at ProviderManager.getProvider (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:145:24)       
    at ProviderManager.getTorrentDetails (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:126:17) 
    at getTorrents (C:\Users\Ajan JaiRam\Desktop\TelegramBot\eg1.js:5:43)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JimmyLaurent** [comment]
There's also an error on the `getTorrentDetails` line, this function returns the details of only one torrent: 

```js
    const result = await TorrentSearchApi.getTorrentDetails(torrents[0]);
    console.log(result);
```

**Comment by ajanjairam** [comment]
> 
> 
> There's also an error on the `getTorrentDetails` line, this function returns the details of only one torrent:
> 
> ```js
>     const result = await TorrentSearchApi.getTorrentDetails(torrents[0]);
>     console.log(result);
> ```

Thanks for your support, where can i find the syntax examples for all different torrent providers, i'm asking this because when i use torrent providers except **Torrent9**, i get the below error

(node:8144) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'provider' of undefined
    at ProviderManager.getTorrentDetails (C:\Users\Ajan JaiRam\Desktop\TelegramBot\node_modules\torrent-search-api\lib\ProviderManager.js:126:37)
    at getTorrents (C:\Users\Ajan JaiRam\Desktop\TelegramBot\eg1.js:5:43)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JimmyLaurent** [comment]
It's the same syntax for all providers.
From what I can see in the stacktrace, I think you're passing an `undefined` value to the  `getTorrentDetails` function. I assume you didn't have any result from the search.

**Comment by ajanjairam** [comment]
> 
> 
> It's the same syntax for all providers.
> From what I can see in the stacktrace, I think you're passing an `undefined` value to the `getTorrentDetails` function. I assume you didn't have any result from the search.

whenever i use pirate bay i get this error

**(node:13924) UnhandledPromiseRejectionWarning: RequestError: Error: getaddrinfo ENOTFOUND thepiratebay.vip**

**Comment by JimmyLaurent** [comment]
ThePirateBay.vip is blocked by your ISP, try to find another tpb proxy that works for you and change it like this:

```js
TorrentSearchApi.overrideConfig('thepiratebay', { baseUrl: 'https://pirateproxy.surf' });
```

**Comment by ajanjairam** [comment]
> ThePirateBay.vip is blocked by your ISP, try to find another tpb proxy that works for you and change it like this:
> 
> ```js
> TorrentSearchApi.overrideConfig('thepiratebay', { baseUrl: 'https://pirateproxy.surf' });
> ```

I used the same code and got the below error (https://pirateproxy.surf is accessible in my ISP)

**(node:19232) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'provider' of undefined**

**Comment by JimmyLaurent** [comment]
I updated TPB provide, with a new api (apibay). 
You should be good to go with the last version 2.1.2.
