### ISSUE TITLE
Can't Deploy in Heroku

### ISSUE THREAD

**Issue by ajanjairam** [JimmyLaurent/torrent-search-api#108]
i created a code using torrent-search-api, and it is well working when i run it in my computer. But when i try to deploy it in Heroku, it dosen't work. If there is a another deploy website in which i can deploy the code made using torrent-search-api, then reply with that website, or make torrent-search-api deployable in Heroku

**Comment by JimmyLaurent** [comment]
You'll have to be more specific here. What kind of error do you have ? Wich code ? Which provider ?

I had no problem using this library on heroku so far.

**Comment by ajanjairam** [comment]
> You'll have to be more specific here. What kind of error do you have ? Wich code ? Which provider ?
> 
> I had no problem using this library on heroku so far.

While deploying in heroku the torrent results take more than 2 minutes

**Comment by JimmyLaurent** [comment]
Maybe it is the connection between you and one of the providers or maybe you don't have enough cpu ? If it's working well on your side, it may be related to heroku more than this library.
Try to investigate, and if you find some concrete issue, I'll be happy to look into it.

In the meantime, I'm not sure to see what I can do about that.
