### ISSUE TITLE
On browser usage

### ISSUE THREAD

**Issue by atuaimi** [JimmyLaurent/torrent-search-api#15]
Is there a way to use the library on the browser; for example to be part of an Angular or Ionic application.

I tried to do so. Some functions like `getProviders()` work fine but when I use `search(..)`, I get this error message: `TypeError: superagent.agent is not a function`

Thanks,

**Comment by JimmyLaurent** [comment]
No it's not possible.

In the browser you can't do cross domain requests unless CORS is enabled on the website you want to query.

You can still expose the library through a rest api but you'll need a backend.

**Comment by atuaimi** [comment]
Assuming CORS can be solved somehow (CORS proxy for example). Do you think the module can easily be modified to run on browser? It seems that the only problem is superagent.agent which only exists in the node environment.

**Comment by JimmyLaurent** [comment]
If the only problem is the superagent.agent in  `x-ray-crawler `, you only have to replace this dependency with something else like fetch, axios or another library.
