### ISSUE TITLE
YggTorrent download failed

### ISSUE THREAD

**Issue by kevinliteon** [JimmyLaurent/torrent-search-api#17]
Hey ! First, thx for your share :+1: 

However, content of my torrent file when i use downloadTorrent function is "Vous devez vous connecter pour télécharger un torrent" with YggTorrent provider.
Someone else have this issue ?

**Comment by JimmyLaurent** [comment]
Thanks for the report.
It was due to the recent change of yggtorrent subdomain. 
You should be good with the last version.

**Comment by kevinliteon** [comment]
Thanks Jimmy !

Le 10 déc. 2017 4:50 PM, Jim <notifications@github.com> a écrit :

Closed #17<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJimmyLaurent%2Ftorrent-search-api%2Fissues%2F17&data=02%7C01%7C%7C13085415d61c4049be0d08d53fe5c5d9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636485178447616511&sdata=FcuoJX6Sk30TQzPn9VK6XXa18mAfDqBXv9jAub%2FWjKA%3D&reserved=0>.
