### ISSUE TITLE
[question] pagination ?

### ISSUE THREAD

**Issue by smolleyes** [JimmyLaurent/torrent-search-api#20]
hi

how can we paginate with this package?

thanks

**Comment by smolleyes** [comment]
and sort by

**Comment by smolleyes** [comment]
if i understand the code, you ask a limit then fetch x page, this is bad to me, better to keep an index of totalResults for each engine, then split by defaultResultsPerPage for each engine, then just ask a start point (working on this), what about a regulary update object like this, (don t care about pageLoading and engine_name..) but for the providers array 

`TorrentSearchApi {engine_name: "global", pageLoading: false, providers: Array(1)}
engine_name
:
"global"
pageLoading
:
false
providers
:
Array(1)
0
:
categories
:
(11) ["All", "Videos", "Movies", "TV", "Emulation", "Games", "Applications", "Music", "Books", "GPS", "XXX"]
currentPage
:
1
currentQuery
:
"dvdrip"
currentqueryTotalPages
:
2
currentquerytotalResults
:
50
name
:
"Yggtorrent"
nextPageStartIndex
:
25
public
:
false`

**Comment by JimmyLaurent** [comment]
I don't plan to include "sortBy" or "pagination" features because I prefer to keep the api simple and heterogeneous.

Still:
- pagination is possible but it means that you need to:
      * modify providers "searchUrl" to include a page number
      * modify providers base class to make queries including the "pageNumber"

    => multi search feature will be inconsistent

- sortBy is not always avalaible on websites. 

     => search feature will be inconsistent
