### ISSUE TITLE
Category search within multiple providers

### ISSUE THREAD

**Issue by ziacik** [JimmyLaurent/torrent-search-api#22]
It is a nice feature to be able to search from multiple providers by enabling the providers and calling a single search function.

But, because the categories are heterogeneous between the providers, the category search is a bit impractical.

I mean, doing this `torrentSearch.search('1080', 'Movies')` skips TPB provider, as the Movie category is not defined on that provider. Furthermore, the possible categories in TPB are actually more grained than defined in the provider (e.g. there is a HD Movies category which is a subcategory of Videos).

It would be nice to either have some kind od mapping which would unify the categories of all providers, or be able to pass a provider/category map as the parameter to the search function.

**Comment by JimmyLaurent** [comment]
I agree, it's not perfect. I'll see if I can do something.

Meanwhile, you can inject your categories in the provider if you want to:

```js
const TorrentSearchApi = require('torrent-search-api');

torrentSearch.enableProvider('thepiratebay');
let tpbCategoriesObjectRef = torrentSearch._getProvider('thepiratebay').scrapeDatas.categories;

// Inject alias
tpbCategoriesObjectRef.Movies = tpbCategoriesObjectRef.Video;

// Inject a new category
tpbCategoriesObjectRef['3D'] = '209';

torrentSearch.search('1080', '3D', 100)
     .then(torrents => {
         console.log(torrents);
     })
     .catch(err => {
         console.log(err);
     });
```

**Comment by JimmyLaurent** [comment]
Providers configs are now overridable, it can be used to create alias and add common searchable categories.
