### ISSUE TITLE
Standard JS formatting

### ISSUE THREAD

**Issue by ylon** [JimmyLaurent/torrent-search-api#24]
Hello,
would you be ok to use standardjs formatting, or tell what kind of formatting you're using. 
because now seems difficult to merge.
if you can want I can make a PR.
regards

**Comment by JimmyLaurent** [comment]
Hi,
You're right, it's missing. 
I like to use prettier to format my code.

This is my config:
```
"prettier": {
    "singleQuote": true,
    "trailingComma": "none",
    "parser": "flow",
    "semi": true,
    "tabWidth": 2
  }
```

I'll take care of adding it to the project. Thanks.

**Comment by ylon** [comment]
Thanks, 
I have installed `prettier-atom`.
the result i got is different than yours. expanding more, respecting max line length, 
cf: [https://github.com/prettier/prettier#intro]()

**Comment by JimmyLaurent** [comment]
Yeah, I plan to use prettier on "torrent-search-api", but I didn't do it yet.
So it's normal if it's different. I'll do it when I have some time.

**Comment by JimmyLaurent** [comment]
@ylon : I made the changes
