### ISSUE TITLE
with npm, there are lot of folders, which files?

### ISSUE THREAD

**Issue by frsdgh** [JimmyLaurent/torrent-search-api#25]
I've installed with npm, there are lot of folders. I got confused which files I need to attach. sorry I dont have much more experience with npm or I am not a professional.

**Comment by JimmyLaurent** [comment]
I'm not sure to understand what you're trying to do.
What do you want to attach ?

**Comment by frsdgh** [comment]
attach the js file, like attach jquery file to html.
appreciate for any clue

**Comment by frsdgh** [comment]
Oh, I got it. I was looking forward to attaching it to HTML like jquery. That's just for nodejs platform, right?
