### ISSUE TITLE
Parse redirected page

### ISSUE THREAD

**Issue by felangga** [JimmyLaurent/torrent-search-api#3]
How to parse redirected page such as ISOHUNT, the download button and magnet buttons are on detail page, there are no download button / magnet button on search result page.

**Comment by JimmyLaurent** [comment]
if you don't need all the torrents links, try to override the download method like 1337x and zetorrents providers.

If you really need all the torrents links override the search method to add a step where you fetch each torrent detail page and get all the download links one by one.

**Comment by felangga** [comment]
Using _downloadTorrent callback ?

**Comment by JimmyLaurent** [comment]
Yes

**Comment by felangga** [comment]
hmm, but the link doesn't show on search request

**Comment by JimmyLaurent** [comment]
No, if you want the links on the search request, you have to override the search method and add a loop to fetch all the torrents details pages and get the download link.

**Comment by felangga** [comment]
Oh okay, I will try that later. Thanks
