### ISSUE TITLE
TorrentLeech Provider Not Working

### ISSUE THREAD

**Issue by usebosespeakers** [JimmyLaurent/torrent-search-api#36]
The TorrentLeech Provider no longer searches. I have tried updating the cookie contents and it does not work. I have tried with versions 1.1.3 and 1.1.4.

**Comment by JimmyLaurent** [comment]
I don't have an account anymore.
I'd be happy to fix it if I can borrow an account or get an invit.

**Comment by oreleraki** [comment]
@usebosespeakers Fix has been updated and after @JimmyLaurent will review it, it should be in :+1:

**Comment by oreleraki** [comment]
@JimmyLaurent, Thanks for the merge, i think we could close this one.

**Comment by JimmyLaurent** [comment]
@oreleraki Thank you for your work , I'm planning to publish a release on npm with new providers and fixes for the broken ones by the end of the week. 
I'll close the issue when it's done.
