### ISSUE TITLE
Login error on Ygg

### ISSUE THREAD

**Issue by YouriT** [JimmyLaurent/torrent-search-api#37]
It seems that the authentication with Ygg started to fail. I tried to debug it but I'm lacking of time to go further now. Will look at it deeper tomorrow most probably. But basically the torrent download fails because Ygg is responding: "Vous devez vous connecter pour télécharger un torrent"

Hence my guess is a trouble with the cookie that is stored in the cookieJar.

**Comment by YouriT** [comment]
So the problem is quite simple `https://yggtorrent.is` became `https://ww1.yggtorrent.is`. But the `followRedirect` of `request` seems to do a bad job at it when it's a `POST` request. A suggestion would be to add a probe to the `torrent-provider` and in case there is a redirect, replacing the `baseUrl` automatically. I'll put that together in a PR.

**Comment by JimmyLaurent** [comment]
Did you try only replacing the baseUrl with "https://ww1.yggtorrent.is" ?

**Comment by YouriT** [comment]
Yup I did and it worked, it's part of my PR. But as a safety net for the future, I believe that dynamic change of the baseUrl like proposed in the PR is worth no?

**Comment by Jeoffreybauvin** [comment]
And now it's ww2...

**Comment by JimmyLaurent** [comment]
Already fixed
