### ISSUE TITLE
getTorrentDetails() for torrents from Yggtorrent return null

### ISSUE THREAD

**Issue by Qualinost1** [JimmyLaurent/torrent-search-api#51]
It's me again. (sorry for the spam)
Is there any way to fix this? It works fine for other providers like torrent9 but for Yggtorrent it always return null.
I tried to find the element "description" in the source code of the website torrent page but it seems that they maybe changed this div name by "default".

**Comment by JimmyLaurent** [comment]
I made the changes, upgrade to 2.0.4 and you should be good.

**Comment by Qualinost1** [comment]
Awesome, thanks!!
