### ISSUE TITLE
Download a torrent.

### ISSUE THREAD

**Issue by emnoze** [JimmyLaurent/torrent-search-api#52]
Hi,
I'm trying to get a single download link.

When I put my search request with

`  app.post('/search2', torrent_controller.searchNewTorrent);`

`exports.searchNewTorrent = async (req, res) => {
  const term = req.body.term;
  const torrents =  await TorrentSearchApi.search(['YggTorrent'], term, 'Movies');
};`

I display a list of results, however, I do not know how to make a link to download ONE torrent without having to search directly on itself. Is there an opportunity to downloadById?
Thank you

**Comment by JimmyLaurent** [comment]
I'm not sure to understand your problem.

You have an endpoint "/search2" that returns a list of torrents matching your "term" value.
Then you want to download a torrent from the list ?

If so, you should create a second endpoint to download the torrent, something like this:

```js
// pseudo code to expose a download endpoint (server side)
app.post('/download', async (req, res) => {
  const buffer = await TorrentSearchApi.downloadTorrent(req.body);
  res.send(buffer);
});

// pseudo code to download a torrent (client side)
const torrents = await axios.post('/search2', {term}).then(r => r.data);
const firstTorrent = torrents[0];
const torrentBuffer = await axios.post('/download', firstTorrent).then(r => r.data);
```
Additionnal note: carreful with security, someone could maybe forge a request to download stuffs via your server.
