### ISSUE TITLE
Ygg url updater

### ISSUE THREAD

**Issue by wesfox** [JimmyLaurent/torrent-search-api#53]
Hey, 

Ygg url have been update, from `https://ww3.yggtorrent.gg` to `https://www2.yggtorrent.gg`

Btw, thank's for this awesome packag, I'm building a web UI over it : https://github.com/wesfox/TorAPI, it's far from being finished but it's on it's way :)

**Comment by JimmyLaurent** [comment]
I'm glad you like it, happy coding.
