### ISSUE TITLE
No Active Providers

### ISSUE THREAD

**Issue by e-moran** [JimmyLaurent/torrent-search-api#56]
The function .getActiveProviders() returns [] and .isActiveProvider() returns false when I am able to access them in my browser. As well as this a .search() function fails to complete.

**Comment by JimmyLaurent** [comment]
I'm not sure to understand, you're calling the library from the browser ? 
If so, it's normal, this is a node package.

**Comment by e-moran** [comment]
Yeah, I misunderstood the purpose of the getActiveProviders() function. I thought it checked whether a provider was accessible rather than whether it had been previously enabled.
