### ISSUE TITLE
Yggtorrent download not working (login)

### ISSUE THREAD

**Issue by nimaskji** [JimmyLaurent/torrent-search-api#57]
Hi

First thx for your job :-)
Actually when  I'm using the downloadTorrent to download file from YGGTorrent provider I got "Vousd evez vous connecter pour télécharger un torrent" .

I already check if the domain is always good, and it's case... any idea ?

thanks !

**Comment by JimmyLaurent** [comment]
Hi, 
Could you try again ? I tried to reproduce but  couldn't.
