### ISSUE TITLE
Dependency not found:  * _http_common in ./node_modules/http-outgoing/index.js

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [JimmyLaurent/torrent-search-api#58]
Hi Devs,

I have a problem In Vuejs when I am importing the file index.js who has the following code.

**Index.js File**

             `const torrentSearch = require('torrent-search-api');
              torrentSearch.enablePublicProviders();
              
              const movies = async () =>{
                      const torrents = await torrentSearch.search('twilight', 'Movies', 4);
                      const promises = []
  
                      torrents.forEach((e) =>{ promises.push(e) });
                      //console.log(promises);
                     await new Promise.all(promises);
             };
             //movies();
`

I want to use the index.js in another place, but when I import it, it shows me the following error:

_This dependency was not found:
_http_common in ./node_modules/http-outgoing/index.js
 To install it, you can run: npm install --save _http_common_

**Comment by JimmyLaurent** [comment]
Hi, sorry to disappoint you but this is a node library, it means you can't use it in the browser and so in your vue project.
You can still make a backend api and consume it from your project.
