### ISSUE TITLE
Downloading torrent from Yggtorrent is not working anymore

### ISSUE THREAD

**Issue by Jeoffreybauvin** [JimmyLaurent/torrent-search-api#62]
Hi,

Downloading a torrent from yggtorrent is not working : 

`Vous devez vous connecter pour télécharger un torrent`

**Comment by JimmyLaurent** [comment]
Just tested it, it seems to work fine for me.

Could you try again please ?

**Comment by Jeoffreybauvin** [comment]
No, same result. Search is working, but download is not. Here is the code I'm using : 

`
const TorrentSearchApi = require('torrent-search-api');
TorrentSearchApi.enableProvider('YggTorrent', 'jeo', 'password');

var todl = { "title": "Debian-Stretch-v9.5-Mutli-64bits-DVD02-NoTag",
    "time": "2018-10-02T07:53:48.000Z",
    "seeds": 1,
    "peers": 0,
    "size": "4.35Go",
    "desc":
     "https://www2.yggtorrent.gg/torrent/application/linux/323257-debian-stretch-v9+5-mutli-64bits-dvd02-notag",
    "id": "323257",
    "provider": "Yggtorrent",
    "link":
     "https://www2.yggtorrent.gg/engine/download_torrent?id=323257" };

f="/Users/jeo/prout.torrent";
TorrentSearchApi.downloadTorrent(todl, f);
`

The file : 

`$ cat prout.torrent
Vous devez vous connecter pour télécharger un torrent`

**Comment by JimmyLaurent** [comment]
Weird, it's working for me..

I assume you tried to login with your browser and everything is fine.
Could you try with a fresh account ? ip ?
Thx

**Comment by ylon** [comment]
Hi, having same issue, so far:
if you make a search then a download it works
if you just make a download it doesn't
...

**Comment by JimmyLaurent** [comment]
Ok thanks, I reproduced.
I'll look into it now.

**Comment by ylon** [comment]
may be: TorrentProvider.fixUnstableUrl() calls this.clearCookie()

**Comment by JimmyLaurent** [comment]
It seems to be related with this indeed.
If you change the baseUrl of yggtorrent to "https://www.yggtorrent.gg", it works.

**Comment by ylon** [comment]
if you call ensureLogin 
then a make search
then a download it doesn't works.

**Comment by JimmyLaurent** [comment]
It looks like a problem with cloudfare, for some reasons if the first request is a post, it doesn't work (I didn't check, but it may not set the cloudfare cookie).

Anyway, I fixed it by adding an extra get query before the login.
You can try the 2.0.7 release.

**Comment by ylon** [comment]
nice one, thank you.

to avoid copy code in ygg's login you can:
```  
async login() {
    await this.request(this.baseUrl, null, null, false);
    await super.login();
    this.lastLoginTime = Date.now();
  }
```

**Comment by JimmyLaurent** [comment]
Sure, thx for the review.

**Comment by Jeoffreybauvin** [comment]
It's working, thanks @JimmyLaurent  !
