### ISSUE TITLE
`fixUnstableUrl` fails on cloudscraper

### ISSUE THREAD

**Issue by YouriT** [JimmyLaurent/torrent-search-api#66]
When cloudscraper is enabled on a provider, `fixUnstableUrl` will fail resolving the tracker url. The reason is that cloudscaper already handles the redirections in order to resolve the challenge. Hence the statusCode is never 300 and we end up with the [following case](https://github.com/codemanki/cloudscraper/blob/master/index.js#L189).

I gave it a shot at fixing it because I thought it would be quick but it's a bit more tricky than thought. I'll give it another shot this eve or tomorrow I believe.

In the meantime, here is a hack for people in the same situation :

```js
torrentSearch.overrideConfig("Yggtorrent", {
  baseUrl: "https://www2.yggtorrent.ch"
});
```

@JimmyLaurent I'll try having the `fixUnstableUrl` be working as expected but that might not be possible. Hence, would you be fine if I make a PR with a periodical check that alters the `baseUrl` when it finds a redirection? If not, any suggestion?

**Comment by JimmyLaurent** [comment]
Hi @YouriT,
Sorry for the delay (just got internet back at home)

I'll try to look into the "fixUnstableUrl" bug when I have some time .
In the meantime, I updated the baseUrl.

**Comment by JimmyLaurent** [comment]
I close this issue and I will remove the "fixUnstableUrl" feature for now, since it's hacky and the api allow to override the baseUrl, so users can try to implement their own solution if they really want it.
