### ISSUE TITLE
Look for all torrent

### ISSUE THREAD

**Issue by sylflo** [JimmyLaurent/torrent-search-api#69]
Is there a way to look for all torrent using pagination of course
I tried like this `const torrents = await TorrentSearchApi.search('*', 'Movies', 10);`

But without success so far

**Comment by JimmyLaurent** [comment]
If you mean by doing so, you’d expect the 10th page of results, no it’s not possible.

This code search « * » in the « movie » category and return the « 10 » first results.

**Comment by sylflo** [comment]
I am sorry, I probably explained badly myself. First of all I don't mind doing pagination or not.

The thing if I understood correctly there is no way to use star or other characters as a wildcard character like on GNU/Linux for example. 

Would you accept a pull request which does that ? Or it's not something you want in this project ?

**Comment by JimmyLaurent** [comment]
I can't see how you would implement this.

This package is basically a scraper which make search requests on torrent websites (ex: thepiratebay), parse and return results from html pages.

So if the torrent website doesn't support wildcard search, which is often, if not always the case, you can't do it.

But maybe I'm missing something here and you have an idea.
If so, I'd be happy to hear it and why not, implement the feature .

**Comment by sylflo** [comment]
Right it's not possible to use wildcard like you said.

Actually I am more thinking of getting the list of all the torrents on a website for example Torrent9. I know it will not be possible on all the websites and on the ones it's gonna be possible to do so it will be probably super slow. That's why I was talking about using pagination of my very first comment.
