### ISSUE TITLE
Download error with 1337x - Protection prevent download

### ISSUE THREAD

**Issue by ThomasF34** [JimmyLaurent/torrent-search-api#71]
Hi 

I have an issue when i'm trying to download a torrent from 1337x. 
In fact, when we are downloading with itorrents mirror, we face a protection that asks to wait 5 seconds before downloading the torrent. (you can see this [here](https://www.1337x.to/torrent/2632298/Kingsman-The-Golden-Circle-2017-720p-YTS-YIFY/) if you click on itorrents download.) 

I'm receiving the html page as a result from the download. (I guess it's because of the protection since i have these lines in the return buffer)
```html 
 <h1><span data-translate="checking_browser">Checking your browser before accessing</span> itorrents.org.</h1>
    
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
```

Do you know the solution to download the torrent and not the protection page html ?

**Comment by JimmyLaurent** [comment]
Hi Thomas,
Check the dependencies of the project, there's a "cloudscraper" package, it should help you with with the cloudfare protection.
