### ISSUE TITLE
Search in all public providers

### ISSUE THREAD

**Issue by Enfexia** [JimmyLaurent/torrent-search-api#8]
How can I search all public or more than one in public providers.

`torrentSearch.search(['IpTorrents', 'Torrent9'], '1080', 'Movies', 20)
    .then(torrents => {
        console.log(torrents);
    })
    .catch(err => {
        console.log(err);
    });`

When I use that code it returns

`[]`

**Comment by JimmyLaurent** [comment]
It's not perfect but maybe you should try something like this:

`
const TorrentSearchApi = require('torrent-search-api');
const torrentSearch = new TorrentSearchApi();

let publicProviders = torrentSearch.getProviders().filter(p => p.public).map(p => p.name);
publicProviders.map(p => torrentSearch.enableProvider(p));

torrentSearch.search(publicProviders, '1080', 'Movies', 100)
.then(torrents => {
    console.log(torrents);
})
.catch(err => {
    console.log(err);
});`

I will add a method "enablePublicProviders()" in a future version.

**Comment by jigarWala** [comment]
nice and elegant solution !
