### ISSUE TITLE
Fail to download from T411

### ISSUE THREAD

**Issue by KiLMaN** [JimmyLaurent/torrent-search-api#9]
Hi i tried to use the T411 part to find torrents, it's working well.
But when i try to download the torrent it's failling 

I call 
`torrentSearch.downloadTorrent(cachedTorrent)
.then(buffer => {
				_logger.debug (buffer );
			})
			.catch(err => {
				console.log(err);
			});`

With the torrent object  as follow
`title=47.meters.down.2017.french.720p.bluray.x264-lost.mkv, time=23 heures, seeds=232, peers=91, size=3.27 Go, desc=https://t411.si/torrents/55551/47-meters-down-2017-french-720p-bluray-x264-lost-mkv, provider=T411`

And i got the error `Error: options.uri is a required argument` at /torrent-search-api/lib/torrent-provider.js:181:42

**Comment by JimmyLaurent** [comment]
There were some changes on T411, I fixed a selector. 
Upgrade to 1.0.17 and it should be good.
