### ISSUE TITLE
Need help for build script please

### ISSUE THREAD

**Issue by BedoM** [JimmyLaurent/torrent-search-api#93]
Hello,

thank you for your job !

But i dont know, who is my problem..

> const torrentSearch = require('torrent-search-api');
> TorrentSearchApi.enableProvider('Yggtorrent', 'My username', 'MyPassword');
> TorrentSearchApi.getActiveProviders();
> [
>   {
>     name: 'Yggtorrent',
>     public: false,
>     categories: [
>       'All',          'Videos',
>       'Movies',       'TV',
>       'Emulation',    'Games',
>       'Applications', 'Music',
>       'Books',        'GPS',
>       'XXX'
>     ]
>   }
> ]

The command above work perfectly (on console node) but the command below  i not work ..

> async function getTorrents() {
> ...    const torrents = await TorrentSearchApi.search('1080', 'Movies', 20);
> }
> 
> getTorrents()
> 
> Promise { <pending> }

Promise ?

**Comment by Edi-san** [comment]
Having same issue plz help.

**Comment by GregDiego** [comment]
Use like this :

const torrentSearch = require('torrent-search-api');

async function getTorrents() {
const torrents = await torrentSearch('1080', 'Movies', 20);
console.log(torrents)      // return an array of results
}
getTorrents()
