### ISSUE TITLE
Cannot read property 'catch' for silentRejection

### ISSUE THREAD

**Issue by Lewdninja** [JimmyLaurent/torrent-search-api#99]
`TypeError: Cannot read property 'catch' of undefined
    at exports.silentRejection (C:\xxx\xxx\xxx\torrent-scraper\node_modules\torrent-search-api\lib\utils\helpers.js:7:36)
    at C:\xxx\xxx\xxx\torrent-scraper\node_modules\torrent-search-api\lib\ProviderManager.js:109:49
    at Array.map (<anonymous>)
    at ProviderManager.search (C:\xxx\xxx\xxx\torrent-scraper\node_modules\torrent-search-api\lib\ProviderManager.js:109:8)`

This started happening with the latest fix commit/version.

- Edit: downgraded to previous version and it's working fine, not doing anything special either
- my setup is: enable all public providers, disable torrent9, search for tv series

**Comment by JimmyLaurent** [comment]
Can disable yts and tell me if you still have the error ?

**Comment by Lewdninja** [comment]
@JimmyLaurent disabling YTS did indeed fix it.

**Comment by JimmyLaurent** [comment]
I released a new version 2.1.1 with the fix.

If you use an http proxy, set env variables HTTP_PROXY and/or HTTPS_PROXY and you should be good.

**Comment by Lewdninja** [comment]
I would like to rotate the proxies so env variable is not the most ideal option. No worries though. Thanks for the fix.
